project:
  type: website
  output-dir: docs

website:
  title: "MF9130E - V23"
  description: "Homepage for MF9130E - Introduction to Statistics at University of Oslo, Spring 2023"

  navbar: 
    left: 
      - href: index.qmd
        text: "Home"
      - href: get_started/get_started.qmd
        text: "Get Started"
      - href: course_material/course_material_overview.qmd
        text: "Course material"
      - href: lab/overview.qmd
        text: "R Lab and Code"
      - href: about.qmd
        text: "About"
        
    right: 
      - icon: github
        href: https://github.com/ocbe-uio/teaching_mf9130e

  page-navigation: true



format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: source

